### ISSUE TITLE
How to use native themeData when using flex_color_scheme

### ISSUE THREAD

**Issue by laterdayi** [rydmike/flex_color_scheme#192] opened 2023-10-02 13:47 UTC
For example, I want to set, 'inputDecorationTheme: const InputDecorationTheme(isDense: true) 'and retain'  flex_color_scheme `s  'inputDecoratorRadius: 35.0 '

**Comment by rydmike** [comment] 2023-10-04 20:07
This is now also demonstrated here https://github.com/rydmike/flex_color_scheme/issues/193#issuecomment-1747554892 with an example, so I'm closing this as kind of duplicate of that more detailed case and example.

**Closed by rydmike** 2023-10-04 20:07 UTC
Labels: duplicate, question
