### ISSUE TITLE
BackdropFilter not working

### ISSUE THREAD

**Issue by minh-le-bliksund** [rydmike/flex_color_scheme#270] opened 2024-12-26 08:56 UTC
I'm having trouble with making the background blur when showing ModalBottomSheet. This only happen when using theme from the package, using the stock Flutter theme is working fine for me.

This is the code to render the bottom sheet:
```
Container(
      color: Colors.transparent,
      child: DraggableScrollableSheet(
        expand: false,
        initialChildSize: 0.5,
        minChildSize: 0.25,
        maxChildSize: 0.9,
        snap: true,
        snapSizes: const [0.25, 0.5, 0.75, 0.9],
        builder: (context, scrollController) => Container(
          color: Colors.transparent,
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
            child: SafeArea(
              child: Container(
                decoration: BoxDecoration(
                  color: ColorScheme.of(context).surface,
                  borderRadius: const BorderRadius.only(
                    topLeft: Radius.circular(20),
                    topRight: Radius.circular(20),
                  ),
                ),
                child: ClipRRect(
                  borderRadius: const BorderRadius.only(
                    topLeft: Radius.circular(20),
                    topRight: Radius.circular(20),
                  ),
                  child: ListView.builder(
                    controller: scrollController,
                    itemCount: viewModel.quotes.length,
                    itemBuilder: (context, index) {
                      return ...;
                    },
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
```

* How it is at the moment:
![image](https://github.com/user-attachments/assets/7bf27507-de2e-444b-b56d-94a4c83fbd07)

* How it looks using the default theme:
![image](https://github.com/user-attachments/assets/a65e525e-567f-4cdc-9d28-cf98d9da1383)

**Comment by rydmike** [comment] 2024-12-26 12:59
Thanks @minh-le-bliksund for the report.

Sounds interesting, can you please post a more full, but minimal runnable code reproduction sample where it **works as expected** and one where it does not when you add the FlexColorScheme based ThemeData?

Please also mentioned the used **Flutter** and **FlexColorScheme** **versions**.

**FlexColorScheme** only produces a **ThemeData** object, so for it to do something out of scope of what ThemeData can also do, is not feasible. However, it can of course potentially produce ThemeData that has unexpected Colors in its `ColorScheme` and that could of course produce undesired results.

Looking forward to learning more about what is going on in this case.

**Comment by minh-le-bliksund** [comment] 2024-12-27 03:07
Hi @rydmike, thanks for the prompt response.

I'm using `Flutter 3.27.1 stable` with `stacked` framework and `FlexColorScheme 8.0.2`.

This is my `flutter doctor -v` output:
![image](https://github.com/user-attachments/assets/c664dc7d-b2bd-4280-97b2-09a96e804f48)

`main.dart` where it works as expected:
```dart
class MainAppWorks extends StatelessWidget {
  const MainAppWorks({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        themeMode: ThemeMode.light,
        home: Home(),
      );
}
```

`main.dart` where it doesn't work as expected:
```dart
class MainAppDoesNotWork extends StatelessWidget {
  const MainAppDoesNotWork({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        theme: AppTheme.light,
        darkTheme: AppTheme.dark,
        themeMode: ThemeMode.light,
        home: Home(),
      );
}
```

`theme.dart (this was generated by the playground)`:
```dart
sealed class AppTheme {
  // The defined light theme.
  static ThemeData light = FlexThemeData.light(
    scheme: FlexScheme.purpleM3,
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 1,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      blendOnLevel: 8,
      useM2StyleDividerInM3: true,
      splashType: FlexSplashType.inkSplash,
      defaultRadius: 12.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.primary,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.primary,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorIsFilled: true,
      inputDecoratorBackgroundAlpha: 31,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 1.0,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
      fabUseShape: true,
      fabAlwaysCircular: true,
      fabSchemeColor: SchemeColor.tertiary,
      popupMenuRadius: 8.0,
      popupMenuElevation: 3.0,
      alignedDropdown: true,
      drawerIndicatorRadius: 12.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetModalBackgroundColor: SchemeColor.surfaceDim,
      bottomSheetRadius: 20.0,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarMutedUnselectedIcon: false,
      menuRadius: 8.0,
      menuElevation: 3.0,
      menuBarRadius: 0.0,
      menuBarElevation: 2.0,
      menuBarShadowColor: Color(0x00000000),
      searchBarElevation: 1.0,
      searchViewElevation: 1.0,
      searchUseGlobalShape: true,
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorRadius: 12.0,
      navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationRailUseIndicator: true,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 1.00,
      navigationRailIndicatorRadius: 12.0,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepPrimary: true,
    ),
    tones: FlexSchemeVariant.jolly.tones(Brightness.light),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );
  // The defined dark theme.
  static ThemeData dark = FlexThemeData.dark(
    scheme: FlexScheme.purpleM3,
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 2,
    darkIsTrueBlack: true,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      blendOnLevel: 10,
      blendOnColors: true,
      useM2StyleDividerInM3: true,
      splashType: FlexSplashType.inkSplash,
      adaptiveElevationShadowsBack: FlexAdaptive.all(),
      defaultRadius: 12.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.primary,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.primary,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorIsFilled: true,
      inputDecoratorBackgroundAlpha: 43,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 1.0,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
      fabUseShape: true,
      fabAlwaysCircular: true,
      fabSchemeColor: SchemeColor.tertiary,
      popupMenuRadius: 8.0,
      popupMenuElevation: 3.0,
      alignedDropdown: true,
      drawerIndicatorRadius: 12.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetModalBackgroundColor: SchemeColor.transparent,
      bottomSheetRadius: 20.0,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarMutedUnselectedIcon: false,
      menuRadius: 8.0,
      menuElevation: 3.0,
      menuBarRadius: 0.0,
      menuBarElevation: 2.0,
      menuBarShadowColor: Color(0x00000000),
      searchBarElevation: 1.0,
      searchViewElevation: 1.0,
      searchUseGlobalShape: true,
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorRadius: 12.0,
      navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationRailUseIndicator: true,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 1.00,
      navigationRailIndicatorRadius: 12.0,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
    ),
    tones: FlexSchemeVariant.jolly.tones(Brightness.dark).surfacesUseBW(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );
}
```

`home.dart`:
```dart
class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        body: SafeArea(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              Text(
                'Hello, STACKED!',
                style: Theme.of(context).textTheme.headlineLarge,
              ),
              Text(
                'Hello, STACKED!',
                style: Theme.of(context).textTheme.headlineLarge,
              ),
              Text(
                'Hello, STACKED!',
                style: Theme.of(context).textTheme.headlineLarge,
              ),
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.dark_mode),
          onPressed: () => showModalBottomSheet(
            context: context,
            isScrollControlled: true,
            isDismissible: true,
            barrierColor: Colors.black.withAlpha(128),
            backgroundColor: Colors.transparent,
            useRootNavigator: true,
            builder: (context) => Container(
              color: Colors.transparent,
              child: DraggableScrollableSheet(
                expand: false,
                initialChildSize: 0.5,
                minChildSize: 0.25,
                maxChildSize: 0.9,
                snap: true,
                snapSizes: const [0.25, 0.5, 0.75, 0.9],
                builder: (context, scrollController) => Container(
                  color: Colors.transparent,
                  child: BackdropFilter(
                    filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                    child: SafeArea(
                      child: Container(
                        decoration: BoxDecoration(
                          color: ColorScheme.of(context).onSurface,
                          borderRadius: const BorderRadius.only(
                            topLeft: Radius.circular(20),
                            topRight: Radius.circular(20),
                          ),
                        ),
                        child: ListView.builder(
                          controller: scrollController,
                          itemCount: 10,
                          itemBuilder: (context, index) => ListTile(
                            title: Text(
                              'Item $index',
                              style: TextTheme.of(context)
                                  .titleMedium!
                                  .copyWith(color: Colors.white),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      );
}
```

Result:
MainAppWorks:
![image](https://github.com/user-attachments/assets/b113220e-a40d-4c9e-9bc2-371f69ffda26)

MainAppDoesNotWork:
![image](https://github.com/user-attachments/assets/c93aced9-e651-4b9d-a83d-2e183a453144)

**Comment by rydmike** [comment] 2024-12-27 14:40
Thanks @minh-le-bliksund for the additional reproduction details. I can confirm that I can repeat this issue. This is a very interesting find and I am looking into it.

I am not sure yet what triggers it, but I am investigating it. I do suspect that doing the same theme in vanilla `ThemeData` will trigger this too, but I have no idea yet what triggers it, I will need to narrow it down.

I did notice that if you remove `subThemesData` property from the `FlexThemeData` entirely the issue goes away. If I even put in just an empty `subThemesData: const FlexSubThemesData()` that enables using some of the FlexColorScheme component defaults, the issue appears.

So apparently something one of the **FlexColorScheme** component themes does, will trigger this. Just need to figure out exactly what and then see if it is something `FlexColorScheme` does in a strange way. The issue is of course that at the end of the day it only makes a bunch of Flutter component themes, so potentially you can do the same thing with vanilla `ThemeData` and if that is the case, it might be an issue in the Flutter framework itself.

Anyway, thanks for posting this find, it is a very interesting case. I'll get back to you when I have looked into it more. I have time for it tonight.

**Comment by rydmike** [comment] 2024-12-27 19:39
I located the source of the issue. If you change the vanilla `ThemeData` in  `MainAppWorks` version to:


```dart
class MainAppWorks extends StatelessWidget {
  const MainAppWorks({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        theme: ThemeData(
          bottomSheetTheme: const BottomSheetThemeData(
            clipBehavior: Clip.antiAlias,
          ),
        ),
        darkTheme: ThemeData.dark(),
        themeMode: ThemeMode.light,
        home: const Home(),
      );
}
```

You will see the same issue. As I suspected we can repeat this issue with vanilla `ThemeData` as well. 


Setting `clipBehavior` in `BottomSheetThemeData` to anything else than the theme default value `Clip.none` causes this issue. FlexColorScheme defaults it to `Clip.antiAlias`.

I have no idea why the clipping behaves like this, it should only impact clipping content inside the bottom sheet when it has content placed high up that needs to be clipped in order to not exceed the rounded corners of the bottom sheet.

To fix this issue, I will make the clipping an optional theming parameter for the bottom sheet theme and have it default to `Clip.none`, it will be available in **version 8.1.0**.

This issue definitely feels like a **Flutter SDK** issue to me. Let's check with with @TahaTesser, what do you think? Worth a Flutter issue?

While waiting for the release 8.1.0 of FlexColorScheme with a workaround for this **Flutter issue**, you can use `ThemeData.copyWith` to override the value of this property to `Clip.none`.

Here is an example of how to do it when using your example theme:

```dart
sealed class AppTheme {
  // The defined light theme.
  static ThemeData get light {
    ThemeData theme = FlexThemeData.light(
      scheme: FlexScheme.purpleM3,
      surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
      blendLevel: 1,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        blendOnLevel: 8,
        useM2StyleDividerInM3: true,
        splashType: FlexSplashType.inkSplash,
        defaultRadius: 12.0,
        elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
        elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
        outlinedButtonOutlineSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.primary,
        segmentedButtonBorderSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderValueTinted: true,
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorIsFilled: true,
        inputDecoratorBackgroundAlpha: 31,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        inputDecoratorUnfocusedHasBorder: false,
        inputDecoratorFocusedBorderWidth: 1.0,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
        fabUseShape: true,
        fabAlwaysCircular: true,
        fabSchemeColor: SchemeColor.tertiary,
        popupMenuRadius: 8.0,
        popupMenuElevation: 3.0,
        alignedDropdown: true,
        drawerIndicatorRadius: 12.0,
        drawerIndicatorSchemeColor: SchemeColor.primary,
        bottomSheetModalBackgroundColor: SchemeColor.surfaceDim,
        bottomSheetRadius: 20.0,
        bottomNavigationBarMutedUnselectedLabel: false,
        bottomNavigationBarMutedUnselectedIcon: false,
        menuRadius: 8.0,
        menuElevation: 3.0,
        menuBarRadius: 0.0,
        menuBarElevation: 2.0,
        menuBarShadowColor: Color(0x00000000),
        searchBarElevation: 1.0,
        searchViewElevation: 1.0,
        searchUseGlobalShape: true,
        navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
        navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationBarIndicatorSchemeColor: SchemeColor.primary,
        navigationBarIndicatorRadius: 12.0,
        navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
        navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationRailUseIndicator: true,
        navigationRailIndicatorSchemeColor: SchemeColor.primary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailIndicatorRadius: 12.0,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
        navigationRailLabelType: NavigationRailLabelType.all,
      ),
      keyColors: const FlexKeyColors(
        useSecondary: true,
        useTertiary: true,
        keepPrimary: true,
      ),
      tones: FlexSchemeVariant.jolly.tones(Brightness.light),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    );
    // Get the bottom sheet theme data from the theme
    BottomSheetThemeData sheetThemeData = theme.bottomSheetTheme;
    // Return the theme with the bottom sheet theme data updated to not clip
    return theme.copyWith(
      bottomSheetTheme: sheetThemeData.copyWith(
        // Set clip behavior to none, so we can avoid the issue.
        clipBehavior: Clip.none,
      ),
    );
  }

  // The defined dark theme.
  static ThemeData get dark {
    ThemeData theme = FlexThemeData.dark(
      scheme: FlexScheme.purpleM3,
      surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
      blendLevel: 2,
      darkIsTrueBlack: true,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        blendOnLevel: 10,
        blendOnColors: true,
        useM2StyleDividerInM3: true,
        splashType: FlexSplashType.inkSplash,
        adaptiveElevationShadowsBack: FlexAdaptive.all(),
        defaultRadius: 12.0,
        elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
        elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
        outlinedButtonOutlineSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.primary,
        segmentedButtonBorderSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderValueTinted: true,
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorIsFilled: true,
        inputDecoratorBackgroundAlpha: 43,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        inputDecoratorUnfocusedHasBorder: false,
        inputDecoratorFocusedBorderWidth: 1.0,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
        fabUseShape: true,
        fabAlwaysCircular: true,
        fabSchemeColor: SchemeColor.tertiary,
        popupMenuRadius: 8.0,
        popupMenuElevation: 3.0,
        alignedDropdown: true,
        drawerIndicatorRadius: 12.0,
        drawerIndicatorSchemeColor: SchemeColor.primary,
        bottomSheetModalBackgroundColor: SchemeColor.transparent,
        bottomSheetRadius: 20.0,
        bottomNavigationBarMutedUnselectedLabel: false,
        bottomNavigationBarMutedUnselectedIcon: false,
        menuRadius: 8.0,
        menuElevation: 3.0,
        menuBarRadius: 0.0,
        menuBarElevation: 2.0,
        menuBarShadowColor: Color(0x00000000),
        searchBarElevation: 1.0,
        searchViewElevation: 1.0,
        searchUseGlobalShape: true,
        navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
        navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationBarIndicatorSchemeColor: SchemeColor.primary,
        navigationBarIndicatorRadius: 12.0,
        navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
        navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationRailUseIndicator: true,
        navigationRailIndicatorSchemeColor: SchemeColor.primary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailIndicatorRadius: 12.0,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
        navigationRailLabelType: NavigationRailLabelType.all,
      ),
      keyColors: const FlexKeyColors(
        useSecondary: true,
        useTertiary: true,
      ),
      tones: FlexSchemeVariant.jolly.tones(Brightness.dark).surfacesUseBW(),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    );
    // Get the bottom sheet theme data from the theme
    BottomSheetThemeData sheetThemeData = theme.bottomSheetTheme;
    // Return the theme with the bottom sheet theme data updated to not clip
    return theme.copyWith(
      bottomSheetTheme: sheetThemeData.copyWith(
        // Set clip behavior to none, so we can avoid the issue.
        clipBehavior: Clip.none,
      ),
    );
  }
}
```
 
You can use this principle as an override to avoid and work around the Flutter issue.

I will keep this issue open until **FlexColorSchemeversion 8.1.0** is released and also in the **Themes Playground** put and info expand ref to this issue for the property. If @TahaTesser thinks it is something that should be fixed in Flutter SDK, we can also file an issue in the Flutter repo.

Thanks @minh-le-bliksund for reporting this issue, a very unusual case and find.

**Comment by TahaTesser** [comment] 2024-12-27 21:58
@rydmike Makes sense to me. This should be reported in Flutter repo.

**Comment by rydmike** [comment] 2024-12-29 17:19
Reopen. Got auto closed when I merged the fix, but not intended to close it until the package is actually released.

**Comment by rydmike** [comment] 2024-12-29 20:15
Added this issue to the Flutter repo here:
https://github.com/flutter/flutter/issues/160963

**Comment by rydmike** [comment] 2024-12-29 20:54
Version 8.1.0 with a fix (workaround) for this issue has been release on pub: https://pub.dev/packages/flex_color_scheme

Closing this issue.

**Closed by rydmike** 2024-12-29 20:54 UTC
Labels: bug Flutter, package, V8

**Comment by minh-le-bliksund** [comment] 2024-12-30 02:04
Hi @rydmike , sorry for my late reply. I can confirm that the new version works as expected. Thanks for quickly resolve this issue (even thought this is an issue in the core Flutter SDK).

**Comment by rydmike** [comment] 2025-01-01 16:19
@minh-le-bliksund I just wanted to update and let you know that using `Clip.none` versus any other clip in the BottomSheet actually works correctly.

They way you use it you actually set the backdrop filter in the BottomSheet and when `Clip.none` is used, it bleeds into the entire page, the bottom sheet itself is also blurred, but since you have a colored container on top if it matching its border, we do not see this.

When a theme then uses some other clip than `Clip.none` on the bottom sheet, it actually cuts and keeps the blur only to the bottom sheet, as the clip should.

Basically you have used background blur on the entire page, also the bottom sheet and then just painted on top of the bottom sheet.

If I change the color of the container to transparent we can demo this:

```dart
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(const IssueApp());

class IssueApp extends StatelessWidget {
  const IssueApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        // theme: AppTheme.light,
        theme: ThemeData(
          bottomSheetTheme: const BottomSheetThemeData(
            clipBehavior: Clip.none,
          ),
        ),
        darkTheme: ThemeData.dark(),
        themeMode: ThemeMode.light,
        home: const Home(),
      );
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        body: SafeArea(
          child: Column(
            children: List.generate(
              15,
              (int index) => Text(
                'This should be blurred',
                style: Theme.of(context).textTheme.headlineLarge,
              ),
            ),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.dark_mode),
          onPressed: () => showModalBottomSheet(
            context: context,
            isScrollControlled: true,
            isDismissible: true,
            barrierColor: Colors.black.withAlpha(128),
            backgroundColor: Colors.transparent,
            useRootNavigator: true,
            builder: (BuildContext context) => Container(
              color: Colors.transparent,
              child: DraggableScrollableSheet(
                expand: false,
                initialChildSize: 0.5,
                minChildSize: 0.25,
                maxChildSize: 0.9,
                snap: true,
                snapSizes: const [0.25, 0.5, 0.75, 0.9],
                builder:
                    (BuildContext context, ScrollController scrollController) =>
                        Container(
                  color: Colors.transparent,
                  child: BackdropFilter(
                    filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                    child: SafeArea(
                      child: Container(
                        decoration: const BoxDecoration(
                          // Use transparent color to see
                          // blur is for entire page and clip will clip it to
                          // the shape of the sheet.
                          color: Colors.transparent,
                          // Original decoration color, we cannot see that it
                          // is blurred, but it is.
                          // ColorScheme.of(context).onSurface,
                          borderRadius: BorderRadius.only(
                            topLeft: Radius.circular(20),
                            topRight: Radius.circular(20),
                          ),
                        ),
                        child: ListView.builder(
                          controller: scrollController,
                          itemCount: 10,
                          itemBuilder: (BuildContext context, int index) =>
                              ListTile(
                            title: Text(
                              'Item $index',
                              style: TextTheme.of(context)
                                  .titleMedium!
                                  .copyWith(color: Colors.white),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      );
}
```

Transparent sheet and `Clip.none`.

![Screenshot 2025-01-01 at 18 07 04](https://github.com/user-attachments/assets/0d6f5f8d-51eb-42d8-9ef2-8bcf3220c4c6)

Transparent sheet and `Clip.antialias`.

![Screenshot 2025-01-01 at 18 05 35](https://github.com/user-attachments/assets/a435824e-3f85-49d8-866e-e1686a5f4a9a)


You are basically using a bit of a side effect of `BackdropFilter` and `ImageFilter.blur` expanding to fill the page and counting on the that content of the bottom sheet is not going to be clipped to its size, and then drawing manually fitted content, including the rounded borders, matching the theme default rounding. If you set another theme rounding on the sheet, it will not match either, unless you change it to use the same value as in theme.

Basically this is the wrong way of doing this effect, but as long as all the config params remain like this and do not change, it will as demonstrated work, but it is a bit of hack that depends on not using clipping on the bottom material sheet, and also inquiring what the default radius for the sheet corners are, or just knowing and hard coding it, like you did.

I should have looked a bit closer at what you were doing in your sample 😃 

The correct and admittedly a bit more complicated way to do this would be to actually do the `BackdropFilter` on the page that the bottom sheet opens up on, triggered when sheet is opened. Then you would not need that extra `Container`, `BoxDecoration` and `BorderRadius` in the bottom sheet at all either, and of course the `BackdropFilter` and `ImageFilter` would not be inside the sheet either.

**Comment by minh-le-bliksund** [comment] 2025-01-02 07:45
Hi @rydmike , I see the issue now.

> The correct and admittedly a bit more complicated way to do this would be to actually do the `BackdropFilter` on the page that the bottom sheet opens up on, triggered when sheet is opened

This is indeed the correct way to do. I have updated my code following this direction, works like a charm.
