### ISSUE TITLE
grey screen in stable release playground

### ISSUE THREAD

**Issue by realth000** [rydmike/flex_color_scheme#256] opened 2024-10-16 19:18 UTC
## Description

Current stable v7 playground seems broken in chrome 130.0.6723.59.

**Can not reproduce in firefox 131.0.3 and Edge 129.0.2792.89**

related link:

* https://rydmike.com/flexcolorscheme/themesplayground-latest/
* https://rydmike.com/flexcolorscheme/themesplayground-v7/

Got a grey screen in chrome browser:

![image](https://github.com/user-attachments/assets/7139bc9c-1dc4-4136-ba99-dd061c64340d)

log:

```console
VM45 content.js:2 Uncaught ReferenceError: MutationEvent is not defined
    at t (VM45 content.js:2:412)
    at VM45 content.js:8:33
    at VM45 content.js:78:176
    at VM45 content.js:78:181
t @ VM45 content.js:2
（匿名） @ VM45 content.js:8
（匿名） @ VM45 content.js:78
（匿名） @ VM45 content.js:78
显示另外 4 个框架
收起
themesplayground-v7/:97 Loading app from service worker.
themesplayground-v7/:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
main.dart.js:48359 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://rydmike.com/flexcolorscheme/themesplayground-v7/assets/fonts/MaterialIcons-Regular.otf
main.dart.js:48359 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://rydmike.com/flexcolorscheme/themesplayground-v7/assets/assets/fonts/FlexIcons.ttf
main.dart.js:48359 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://rydmike.com/flexcolorscheme/themesplayground-v7/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
main.dart.js:36503 Got object store box in database flex_color_scheme_v5_box_5.
main.dart.js:36503 NoSuchMethodError: method not found: 'a6q' on null
main.dart.js:36503     at Object.hs (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:38731:10)
main.dart.js:36503     at Object.ahm (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:37170:8)
main.dart.js:36503     at ayU.$2 (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:63102:11)
main.dart.js:36503     at yn.t (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:133920:20)
main.dart.js:36503     at MU.t (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:133874:20)
main.dart.js:36503     at lv.cO (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:123690:21)
main.dart.js:36503     at lv.lT (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:123662:9)
main.dart.js:36503     at lv.lT (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:123696:11)
main.dart.js:36503     at lv.Iy (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:123631:6)
main.dart.js:36503     at lv.a9S (https://rydmike.com/flexcolorscheme/themesplayground-v7/main.dart.js:123632:19)
```

## Env

* OS: Windows 11
* Browser: Google Chrome 130.0.6723.59

**Comment by rydmike** [comment] 2024-10-16 23:28
Thanks for the report @realth000

I also started noticing loading issues yesterday after some browser updates, or so I thought.

The Playground builds have not changed or been touched since they were built.

But I do agree, something is happening, let's figure out what. My first thoughts where:

* Either browser updates are breaking things that worked before.

**OR**

* The free GitHub Pages static page hosting I'm using is giving up due to too large GitHub Pages repo. It could be this too as I read somewhere there is some limit and I might have reached it.

For reference these are links to different available builds and some initial results I got when testing them on different browsers

| Build Version  | Chrome | Safari | Edge | Brave | Firefox |
| ---------- | ---------- | ----------- | ----------- | ----------- | ---------- | 
| V8 Beta [V8.0.0-dev.1](https://rydmike.com/flexcolorscheme/themesplayground-dev) | OK | OK | OK | OK |  |
| V7 latest [V7.3.1](https://rydmike.com/flexcolorscheme/themesplayground-latest) | OK | OK | FAIL | FAIL |  |
| V7.2 [V7.2.0](https://rydmike.com/flexcolorscheme/themesplayground-v7-2) | OK | OK | FAIL | FAIL |  |
| V7.1 [V7.1.2](https://rydmike.com/flexcolorscheme/themesplayground-v7-1) | FAIL | FAIL | FAIL | FAIL |  |
| V7.0 [V7.0.5](https://rydmike.com/flexcolorscheme/themesplayground-v7) | FAIL | FAIL | FAIL | FAIL |  |
| V6 [V6.1.1](https://rydmike.com/flexcolorscheme/themesplayground-v6) | FAIL | OK | FAIL | FAIL |  |
| V5 [V5.1.0](https://rydmike.com/flexcolorscheme/themesplayground-v5) | FAIL | OK | FAIL | FAIL |  |
| V4 [V4.2.0](https://rydmike.com/flexcolorschemeV4Tut5) | OK | OK | FAIL | OK |  |


Versions tested:
* Chrome 130.0.6723.59 (Official Build) (arm64)
* Safari 18.0.1 (20619.1.26.31.7)
* Edge 129.0.2792.89 (Official build) (arm64)
* Brave 1.70.126 Chromium: 129.0.6668.100 (Official Build) (arm64)
* Firefox, did not test FireFox yet, as I figured out the cause...


Then I think I found the issue as the log tells me this:

```console
Uncaught Error: HiveError: Cannot read, unknown typeId: 199. Did you forget to register an adapter?
    at Object.i (main.dart.js:3031:3)
    at al1.D8 (main.dart.js:136877:20)
    at LJ.aJK (main.dart.js:136612:21)
    at tear_off.<anonymous> (main.dart.js:3153:65)
    at ag.cp (main.dart.js:48890:23)
    at dB.H (main.dart.js:48869:16)
    at main.dart.js:136656:14
    at b6W.a (main.dart.js:4337:62)
    at b6W.$2 (main.dart.js:49751:14)
    at b5L.$1 (main.dart.js:49745:21)
```

Since the the different builds are all under the same domain, they share the same local storage file and name where the settings are stored. And different versions contain different data, and an older version is not necessarily compatible with newer version, so running a newer version may insert data and types into same file that are not compatible with the older version. Ouch!

Well this is mytheory anyway, since I'm getting type conversion errors on older version that belongs to types only used new versions, after running the newer version.

Dang, I should have let each version use a new file name, but then any config data from the old version does not move to the new one, so not ideal either.

Deleting browsing data and then reloading only the specific version URL you need, in that browser, seems to work. Doing that I could get e.g. Chrome to load V7.1 and V7.0, and also eg Brave to load V7 latest, that failed above.

I need to put this info into the doc site for those that have a used a newer version like the 8-0-0-dev.1 version but also need to step down and access a later versions again.

Later with V9 I plan to redo the entire local persistence solution so this kind of thing won't be a problem, and then even later V10 should have cloud storage.

V8 is still the same very simple solution that the app had since V4, since V8 is also just based on the same "tutorial" demo on how to use FlexColorScheme https://docs.flexcolorscheme.com/playground_history#background

**Comment by rydmike** [comment] 2024-10-17 10:57
Added info to the doc site about this

https://docs.flexcolorscheme.com/playground#available-themes-playground-builds

**Comment by realth000** [comment] 2024-10-19 19:38
Thanks, it works after I deleted cookie and storage.

**Comment by rydmike** [comment] 2024-10-21 20:18
Closing this issues since the fix works and this limitation is also mentioned in docs, plus I have changed file name so with next V8 and final V8 release there will not be conflict with V7.

**Closed by rydmike** 2024-10-21 20:18 UTC
Labels: documentation, question
